### ISSUE TITLE
Improve the error story

### ISSUE THREAD

**Issue by drahnr** [Richterrettich/rpm-rs#14]
Currently error handling is quite plain and not sophisticated with passing a lot of `String`s around.

One of my favourites here is [`thiserror`](https://lib.rs/crates/thiserror) since it appears as `std::error::Error` trait impl to the outside world, yet allows convenience to avoid having to implement all enumerations of an enum manually.

**Comment by Richterrettich** [comment]
thiserror looks promising. I'll have a look.
