### ISSUE TITLE
rpms with tag 1008 fail to be parse

### ISSUE THREAD

**Issue by drahnr** [Richterrettich/rpm-rs#16]
If `RPMTAG_INSTALLTIME` is present it won't parse successfully.

Example: https://dl.influxdata.com/telegraf/releases/telegraf-1.14.2-1.x86_64.rpm

**Comment by drahnr** [comment]
Probabliy a false positive.

**Comment by drahnr** [comment]
Fix is in https://github.com/drahnr/rpm-rs/commit/b859bd927f1ba34e4c29ae615069b8ca36de1910

**Comment by Richterrettich** [comment]
this should be fixed now
