### ISSUE TITLE
Release 0.4.1

### ISSUE THREAD

**Issue by drahnr** [Richterrettich/rpm-rs#19]
With the last merge, a few cases were fixed so it would be awesome if we could do a patch release so I can stop patching cargo.toml :)

**Comment by Richterrettich** [comment]
Hi,

I'll do it the upcoming days when I am at home again. I guess I'll release it as 0.5.0 because of some API changes.

**Comment by Richterrettich** [comment]
I've released version 0.5.0 since there where some changes to the API. I also had to update the PGP version since there was a problem building the project with the version chosen by cargo.

**Comment by drahnr** [comment]
Thanks!
