### ISSUE TITLE
How well-tested is this library?

### ISSUE THREAD

**Issue by dralley** [Richterrettich/rpm-rs#2]
Hi!

I found this library and I'm super glad that something like it exists because it's exactly what I need.  The place where I'd like to use this is in a CI pipeline for some software that needs to parse RPMs and generate correct repository metadata for those RPMs.  Currently we just have some RPM files laying around from 8 years ago with no spec files and no good way to regenerate them and we're at the point where where that is a big problem.  

My only hesitation is that I don't know how well-tested it is or whether anyone else is using it or whether it will remain semi-available to accept patches and make releases if bugs are found or we needed to add features.

Can you speak to any of those concerns?

**Comment by Richterrettich** [comment]
Hi and sorry for the late reply. Github notifications are a bit strange.

I use this for some of my projects and we use this at my workplace for CI purposes (to create RPM files). Mostly simple RPM files with a few executables and configuration files. I did not encounter any problems with CentOS and somewhat recent Fedora RPM files for parsing. 
I am very open to patches for this. Especially signing is a feature that is missing.

**Comment by Richterrettich** [comment]
I'll close this issue since I can not give you any more information than already provided. At this point, we have created a lot of RPM's with this library at my workplace with no issues. Feel free to open an issue if you have a more specific question or problem.
