### ISSUE TITLE
Repository Activity 

### ISSUE THREAD

**Issue by drahnr** [Richterrettich/rpm-rs#41]
Hey @Richterrettich 

I hope everything is well, I've noticed that quite a few PRs are waiting for review. I did merge them into https://github.com/drahnr/rpm-rs and publish them as `rpm-rs-temporary` for the time being.

In case you are not interested in development or simply lack time, I'd be happy to chime in and review & merge PRs as needed.

**Comment by Richterrettich** [comment]
Hey!
sorry for being absent, it was kind of a busy time. I am fine and I will pick up development again in the upcoming weeks.
I'll address those open PR's this weekend. Thank you for sticking around.
